version: "3.8"
services:
  nginx:
    container_name: nginx_${COMPOSE_PROJECT_NAME}
    image: nginx:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/templates:/etc/nginx/templates
    networks:
      default:
        ipv4_address: ${COMPOSE_PROJECT_NETWORK}.2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php_fpm_${COMPOSE_PROJECT_NAME}
    image: php_fpm_${COMPOSE_PROJECT_NAME}
    working_dir: /app
    build:
      args:
        user: $COMPOSE_USER_NAME
        uid: $COMPOSE_USER_UID
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      default:
        ipv4_address: ${COMPOSE_PROJECT_NETWORK}.3
  postgres:
    container_name: postgres_${COMPOSE_PROJECT_NAME}
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: "${DB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_ALLOW_EMPTY_PASSWORD: 1
      POSTGRES_ROOT_PASSWORD: "root"
    volumes:
      - ../database:/var/lib/postgresql/data
    ports:
      - "8101:5432"
    networks:
      default:
        ipv4_address: ${COMPOSE_PROJECT_NETWORK}.4
#  mysql:
#    container_name: mysql_${COMPOSE_PROJECT_NAME}
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: "${DB_DATABASE}"
#      MYSQL_USER: "${DB_USERNAME}"
#      MYSQL_PASSWORD: "${DB_PASSWORD}"
#    volumes:
#      - mysql:/var/lib/mysql
#    networks:
#      default:
#        ipv4_address: ${COMPOSE_PROJECT_NETWORK}.5
#  phpmyadmin:
#      container_name: phpmyadmin_${COMPOSE_PROJECT_NAME}
#      image: phpmyadmin:latest
#      environment:
#          PMA_HOST: mysql
#      #    PMA_ABSOLUTE_URI: pma
#      networks:
#          default:
#              ipv4_address: ${COMPOSE_PROJECT_NETWORK}.6
#      depends_on:
#          - mysql
#  redis:
#    container_name: redis_${COMPOSE_PROJECT_NAME}
#    image: redis:alpine
#    restart: always
#    ports:
#      - "8081:8081"
#    networks:
#      default:
#        ipv4_address: ${COMPOSE_PROJECT_NETWORK}.7
volumes:
  mysql:
    driver: local
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${COMPOSE_PROJECT_NETWORK}.0/16
          gateway: ${COMPOSE_PROJECT_NETWORK}.1
